### ISSUE TITLE
💡 Add Ukrainian translation

### ISSUE THREAD

**Issue by stanol** [DonutWare/Fladder#60]
### Summary

I made a Ukrainian translation on [Weblate](https://hosted.weblate.org/projects/fladder/fladder/uk/), but I'm not sure how to properly make a pull request to add it to the application.

### Basic Example

-

### Drawbacks

-

**Comment by bazzadazza72** [comment]
Thank you so much for taking your time to translate Fladder. I just had a quick look at the Weblate page, in order to contribute you'll need to:

- download the `*.arb` file from the Info tab
- fork the repository and clone it to your machine
- add the downloaded `.arb` file to the `lib/i10n` directory, then commit and sync
- open a pull request

If you're uncomfortable with doing all that, I can open a request on your behalf if you'd like

**Comment by PartyDonut** [comment]
@stanol Thank you for adding the translations. It was a joy to see you and everyone else contributing to the translations 😃 .

@bazzadazza72 It's fine to do it manually, but I was planning on integrating the weblate bot to make PR's automatically so we don't have to do it manually. Probably somewhere this week.

**Comment by bazzadazza72** [comment]
> I was planning on integrating the weblate bot to make PR's automatically

That'll be the way to do it. I'll submit this translation, then future translations can be handled by the bot.
